trigger:
    - main
    pool:
      vmImage: ubuntu-latest
    
    stages:
    - stage: CreateArtifact
      displayName: 'Artifact'
      jobs:
        - job: artifact
          displayName: 'Iniciando'
          pool:
            vmImage: ubuntu-latest
          steps:
            - task: CopyFiles@2
              displayName: 'Copiar'
              inputs:
                Contents: '**'
                targetFolder: '$(Build.ArtifactStagingDirectory)'    
            - task: PublishBuildArtifacts@1
              displayName: 'Publicar'
              inputs:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                ArtifactName: 'drop'
                publishLocation: 'Container'
    